language: node_js
node_js:
    - "4"
    - "5"
    - "6"

addons:
    code_climate:
        repo_token: a80533b6bec6be2c2fdf530b3ffcae409eb4603eabfeba0d9b102f26426979c9

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info